"""Render the PR description for an accepted candidate (SPEC §8.4).

The body is the human reviewer's whole context: a before/after metrics table,
the candidate's lineage, the adversarial reviewer's verdict + critique, and links
to the LangSmith trace and held-out results. It ends with an explicit
DO-NOT-AUTO-MERGE notice (anti-pattern §13) — the merge is a human decision.
"""

from __future__ import annotations

from self_improvement.pr_gen.evidence import EvidencePackage, MetricDelta

# Visible banner so neither a human nor an automation mistakes the PR for one
# that may be merged programmatically (SPEC §8.4 / anti-pattern §13).
NO_AUTO_MERGE_NOTICE = (
    "> ⚠️ **Human review required — do NOT auto-merge.** "
    "Self-improvement PRs are merged by a human after reviewing the evidence "
    "below (SPEC §8.4, anti-pattern §13)."
)


def _fmt(value: float) -> str:
    return f"{value:.4f}"


def _delta_row(d: MetricDelta) -> str:
    arrow = "🟢" if d.improved else ("🔴" if d.after < d.before else "⚪")
    pct = "—" if d.pct_change is None else f"{d.pct_change * 100:+.1f}%"
    return f"| `{d.name}` | {_fmt(d.before)} | {_fmt(d.after)} | {d.delta:+.4f} | {pct} | {arrow} |"


def _metrics_table(deltas: list[MetricDelta]) -> str:
    if not deltas:
        return "_No metrics reported._"
    header = "| Metric | Before | After | Δ | % | |\n|---|---|---|---|---|---|"
    rows = "\n".join(_delta_row(d) for d in deltas)
    return f"{header}\n{rows}"


def _lineage_section(pkg: EvidencePackage) -> str:
    if not pkg.lineage:
        return "_Seed candidate — no ancestry._"
    lines = []
    for entry in pkg.lineage:
        summary = f" — {entry.mutation_summary}" if entry.mutation_summary else ""
        h = f" (`{entry.config_hash[:12]}`)" if entry.config_hash else ""
        lines.append(f"- gen {entry.generation}: `{entry.experiment_id}`{h}{summary}")
    return "\n".join(lines)


def _reviewer_section(pkg: EvidencePackage) -> str:
    r = pkg.reviewer
    lines = [f"**Verdict:** `{r.verdict}`"]
    if r.checks:
        for name, passed in sorted(r.checks.items()):
            lines.append(f"- {'✅' if passed else '❌'} {name}")
    if r.critique:
        lines.append(f"\n{r.critique}")
    return "\n".join(lines)


def _links_section(pkg: EvidencePackage) -> str:
    lines = []
    if pkg.langsmith_trace_url:
        lines.append(f"- [LangSmith evaluation trace]({pkg.langsmith_trace_url})")
    if pkg.heldout_results_url:
        lines.append(f"- [Held-out test results]({pkg.heldout_results_url})")
    return "\n".join(lines) if lines else "_No evidence links provided._"


def render_pr_title(pkg: EvidencePackage) -> str:
    """Headline title: the strongest metric movement, or a neutral fallback."""
    improved = pkg.improved_metrics()
    if improved:
        best = max(improved, key=lambda d: d.delta)
        return f"Self-improvement: {best.name} {best.before:.3f}→{best.after:.3f} (exp {pkg.experiment_id})"
    return f"Self-improvement candidate (exp {pkg.experiment_id})"


def render_pr_description(pkg: EvidencePackage) -> str:
    """Render the full PR body markdown from the evidence package (SPEC §8.4)."""
    sections = [
        NO_AUTO_MERGE_NOTICE,
        "## Summary",
        (
            f"Accepted candidate `{pkg.experiment_id}` from run `{pkg.run_id}` "
            "proposes the `index.retrieval` config change below. Evidence follows."
        ),
        "## Eval metrics (before → after)",
        _metrics_table(pkg.metric_deltas),
        "## Candidate lineage",
        _lineage_section(pkg),
        "## Adversarial reviewer report",
        _reviewer_section(pkg),
        "## Evidence links",
        _links_section(pkg),
        "## Proposed config",
        f"```yaml\n{_config_yaml(pkg)}```",
        "---",
        NO_AUTO_MERGE_NOTICE,
        "🤖 Generated by the self-improvement loop (SPEC §8.4).",
    ]
    return "\n\n".join(sections) + "\n"


def _config_yaml(pkg: EvidencePackage) -> str:
    # Local import avoids a module cycle (diff imports nothing from description).
    import yaml

    from self_improvement.pr_gen.diff import pipeline_config_to_retrieval_block

    block = {"index": {"retrieval": pipeline_config_to_retrieval_block(pkg.config)}}
    return yaml.safe_dump(block, sort_keys=False, default_flow_style=False)


__all__ = ["NO_AUTO_MERGE_NOTICE", "render_pr_title", "render_pr_description"]
